### ISSUE TITLE
Could not find 'nosetests.json' in any of the parent folders of the active file.

### ISSUE THREAD

**Issue by VictorCarreira** [thschenk/atom-nosetests#3]
I was trying to run a python code in atom. I have installed the package python-nosetests, but I still can´t running my python code.

The mensage error is reported in the title of this mensage.

Best regards.

**Comment by paul-schwendenman** [comment]
When running nosetests for the first time on a project, go to the project root and run the tests from the command line:

```
(python2) nosetests --with-json-extended
(python3) python3 -m nose --with-json-extended
```

This will generate a file nosetests.json which contains, besides the test results, also the required information to re-run the tests.
